name: PR Checklist Validation

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  checklist:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Validate PR checklist
        run: |
          PR_BODY=$(jq -r .pull_request.body < "$GITHUB_EVENT_PATH")
          echo "PR Body: $PR_BODY"

          REQUIRED_CHECKBOXES=(
            "- \[x\] Run Integration/Convergence Tests"
            "- \[x\] \`julia --project=@. --threads=30 examples/convergence/isentropic-vortex-convergence.jl\`"
            "- \[x\] \`julia --project=@. --threads=30 examples/convergence/leblanc-convergence.jl\`"
            "- \[x\] \`julia --project=@. --threads=30 examples/convergence/wall-convergence.jl\`"
          )

          for CHECKBOX in "${REQUIRED_CHECKBOXES[@]}"
          echo "Searching for checkbox: \"$CHECKBOX\""  # Add this line for debugging
          do
            if ! echo "$PR_BODY" | grep -F "$CHECKBOX"; then
              echo "All checkboxes should be checked before landing."
              exit 1
            fi
          done
